baseURL = 'https://quantk.github.io/obsidian-hugo-demo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-paper"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['templates/**']